# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: new-pr-rec-workflow

on:
  push:
    branches: ["main"]
env:
  ENV_NAME: env
  ENV_VARIABLE: test
  GOOGLE_DRIVE_CLIENT_ID_VAR: '${{ vars.GOOGLE_DRIVE_CLIENT_ID_VAR }}'
  GOOGLE_DRIVE_CLIENT_ID: ${{ secrets.GOOGLE_DRIVE_CLIENT_ID }}
  GOOGLE_DRIVE_API_KEY: '${{ secrets.GOOGLE_DRIVE_API_KEY }}' 
# permissions:
#   contents: read

jobs:  
  set-up-env-variables:
    runs-on: ubuntu-latest
    environment: github-pages
    # env: # Or as an environment variable
      # GOOGLE_DRIVE_CLIENT_ID_VAR: ${{ vars.GOOGLE_DRIVE_CLIENT_ID_VAR }}
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: '20'
      - name: Set ENV VAR
        run: |
          echo "GOOGLE_DRIVE_CLIENT_ID_VAR=${{ vars.GOOGLE_DRIVE_CLIENT_ID_VAR }}" >> $GITHUB_OUTPUT
          echo "GOOGLE_DRIVE_CLIENT_ID_VAR=${{ vars.GOOGLE_DRIVE_CLIENT_ID_VAR }}" >> $GITHUB_ENV
          echo "GOOGLE_DRIVE_API_KEY=${{ secrets.GOOGLE_DRIVE_API_KEY }}" >> $GITHUB_OUTPUT
          echo "GOOGLE_DRIVE_API_KEY=${{ secrets.GOOGLE_DRIVE_API_KEY }}" >> $GITHUB_ENV

      - name: Display ENV VAR
        run: |
          echo "GOOGLE_DRIVE_CLIENT_ID_VAR: $GOOGLE_DRIVE_CLIENT_ID_VAR"
          # echo "ENV_VARIABLE : $ENV_VARIABLE"
          # echo "GOOGLE_DRIVE_CLIENT_ID_VAR=vars.GOOGLE_DRIVE_CLIENT_ID_VAR" >> "$GITHUB_ENV"
          # echo "GOOGLE_DRIVE_CLIENT_ID_VAR: $GOOGLE_DRIVE_CLIENT_ID_VAR"


      # - run: bats -v
      
      # - name: Setup Deno
      #   # uses: denoland/setup-deno@v1
      #   uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
      #   with:
      #     deno-version: v1.x
      #   env: # Or as an environment variable
      #     GOOGLE_DRIVE_CLIENT_ID: '${{ secrets.GOOGLE_DRIVE_CLIENT_ID }}'
      #     GOOGLE_DRIVE_API_KEY: '${{ secrets.GOOGLE_DRIVE_API_KEY }}'

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      # - name: Run linter
      #   run: deno lint

      # - name: Run tests
      #   run: deno test -A
